title: Jefferson Angel Areche Rojas

logo: photo.png

description: Cloud Engineer and eventually Data Scientist and AI Engineer

show_downloads: true

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag

email: jefferson.areche@gmail.com